import { useState } from "react";
import { ArrowDown, ArrowRight, Check, ChevronDown, CirclePlay, Database, FileCheck2, FileSpreadsheet, Menu, MoveRight, ShieldCheck, UploadCloud, X, Zap } from "lucide-react";
import { Brand, SmallArrow, StatusPill, Toast } from "./_shared/Brand";
import "./_group.css";

const features = [
  { icon: Zap, kicker: "01 / Instant", title: "From document to usable data.", body: "Drop in the messiest invoice or receipt. DocuMind recognizes structure, context, and intent in seconds.", stat: "8.4 sec", label: "average extraction" },
  { icon: ShieldCheck, kicker: "02 / Trustworthy", title: "Confidence you can act on.", body: "Every field carries a confidence score and source trace. Review what matters, skip what does not.", stat: "99.2%", label: "field accuracy" },
  { icon: Database, kicker: "03 / Connected", title: "Data that goes somewhere.", body: "Export clean records to your accounting stack, ERP, or data warehouse without rebuilding a workflow.", stat: "42+", label: "native field types" },
];

export function Landing() {
  const [mobile, setMobile] = useState(false);
  const [annual, setAnnual] = useState(true);
  const [toast, setToast] = useState("");
  const notify = (msg: string) => setToast(msg);
  return (
    <main className="dm-root dm-noise">
      <section className="relative min-h-[760px] overflow-hidden">
        <div className="dm-grid pointer-events-none absolute inset-0 opacity-70" />
        <div className="pointer-events-none absolute -right-40 top-8 h-[520px] w-[520px] rounded-full bg-[#15834d]/10 blur-[120px]" />
        <header className="relative z-10 mx-auto flex max-w-[1180px] items-center justify-between px-6 py-6 lg:px-8">
          <Brand />
          <nav className={`${mobile ? "absolute left-4 right-4 top-20 flex" : "hidden md:flex"} items-center gap-8 rounded-2xl border border-[#c7dcc9]/10 bg-[#0d1510]/95 p-4 text-[12px] text-[#95a69a] backdrop-blur-xl md:static md:border-0 md:bg-transparent md:p-0`}>
            <a href="#product" className="transition hover:text-[#e8f0e5]">Product</a><a href="#workflow" className="transition hover:text-[#e8f0e5]">How it works</a><a href="#pricing" className="transition hover:text-[#e8f0e5]">Pricing</a>
            <button onClick={() => notify("Demo request received — we will be in touch.")} className="dm-btn dm-btn-ghost !px-4 !py-2.5">Book a demo <SmallArrow /></button>
          </nav>
          <div className="flex items-center gap-3">
            <button onClick={() => notify("Sign in is ready in the auth preview.")} className="hidden text-[12px] font-semibold text-[#95a69a] transition hover:text-[#e8f0e5] sm:block">Sign in</button>
            <button onClick={() => setMobile(!mobile)} className="rounded-lg border border-[#c7dcc9]/15 p-2 text-[#e8f0e5] md:hidden">{mobile ? <X size={18} /> : <Menu size={18} />}</button>
            <button onClick={() => notify("Your free workspace is waiting in the auth preview.")} className="dm-btn dm-btn-primary !hidden !px-4 !py-2.5 sm:!inline-flex">Start free <SmallArrow /></button>
          </div>
        </header>
        <div className="relative z-10 mx-auto grid max-w-[1180px] gap-16 px-6 pb-24 pt-20 lg:grid-cols-[1.02fr_.98fr] lg:items-center lg:px-8 lg:pt-28">
          <div className="dm-reveal">
            <StatusPill>AI document intelligence</StatusPill>
            <h1 className="dm-display mt-7 max-w-[730px] text-[clamp(3.3rem,7vw,6.6rem)] font-medium leading-[.92] tracking-[-.075em] text-[#e8f0e5]">The quiet power<br />behind <em className="font-normal text-[#9df4b1]">clean data.</em></h1>
            <p className="mt-7 max-w-[520px] text-[16px] leading-7 text-[#95a69a]">DocuMind turns invoices, receipts, and documents into structured editable data instantly — so operations and finance teams can stop entering, and start moving.</p>
            <div className="mt-9 flex flex-wrap items-center gap-3"><button onClick={() => notify("Your workspace is being prepared.")} className="dm-btn dm-btn-primary">Start extracting for free <ArrowRight size={16} /></button><button onClick={() => notify("Playing a 90-second product tour.")} className="dm-btn dm-btn-ghost"><CirclePlay size={15} /> See it in action</button></div>
            <div className="mt-9 flex items-center gap-4 text-[11px] text-[#617167]"><div className="flex -space-x-2">{["AM","JR","KS","NL"].map((i) => <span key={i} className="flex h-7 w-7 items-center justify-center rounded-full border-2 border-[#080c09] bg-[#284b36] text-[9px] font-bold text-[#baf6c5]">{i}</span>)}</div><span>Trusted by 2,400+ finance teams</span><span className="h-1 w-1 rounded-full bg-[#d9b66d]" /><span>No credit card required</span></div>
          </div>
          <div className="dm-reveal dm-delay-2 relative">
            <div className="absolute -inset-10 rounded-full bg-[#39ca72]/10 blur-[90px]" />
            <div className="dm-glass relative overflow-hidden rounded-[26px] p-3 shadow-[0_35px_100px_rgba(0,0,0,.45)]">
              <div className="rounded-[19px] border border-[#c7dcc9]/10 bg-[#0b110d] p-5">
                <div className="flex items-center justify-between border-b border-[#c7dcc9]/10 pb-4"><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#e8f0e5] text-[#173d28]"><FileTextIcon /></span><div><p className="text-[11px] font-semibold text-[#e8f0e5]">invoice_2048.pdf</p><p className="dm-mono mt-1 text-[9px] text-[#617167]">uploaded just now · 1.8 MB</p></div></div><StatusPill>Analyzing</StatusPill></div>
                <div className="relative mt-5 overflow-hidden rounded-xl border border-[#c7dcc9]/10 bg-[#f0f3ec] p-5 text-[#1e2921] shadow-inner"><div className="dm-scan absolute left-0 right-0 top-0 h-10 bg-gradient-to-b from-transparent via-[#39ca72]/45 to-transparent" /><div className="flex justify-between"><div><div className="h-2 w-28 rounded bg-[#aab4a7]" /><div className="mt-2 h-1.5 w-20 rounded bg-[#c2cabd]" /></div><span className="dm-mono text-[9px] text-[#8d958b]">INV-2048</span></div><div className="mt-8 space-y-3"><div className="h-2 w-4/5 rounded bg-[#c8cec4]" /><div className="h-2 w-3/5 rounded bg-[#d2d8cd]" /><div className="grid grid-cols-3 gap-2 pt-2"><div className="h-8 rounded border border-[#d5dbd2]" /><div className="h-8 rounded border border-[#d5dbd2]" /><div className="h-8 rounded border border-[#d5dbd2]" /></div></div><div className="mt-7 flex justify-end"><div className="h-5 w-24 rounded bg-[#a7b4a4]" /></div></div>
                <div className="mt-5 grid grid-cols-2 gap-2"><MiniField label="Vendor" value="Northstar Supply Co." /><MiniField label="Total amount" value="$12,480.00" gold /><MiniField label="Invoice date" value="18 Sep 2024" /><MiniField label="Confidence" value="99.8%" /></div>
                <button onClick={() => notify("All fields marked as reviewed.")} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-[#9df4b1] py-3 text-[11px] font-bold text-[#07110a]"><Check size={14} /> Review extracted fields</button>
              </div>
            </div>
            <div className="dm-glass absolute -bottom-6 -left-8 flex items-center gap-3 rounded-2xl px-4 py-3"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#173d28] text-[#9df4b1]"><ShieldCheck size={15} /></div><div><p className="text-[11px] font-semibold">Source trace attached</p><p className="dm-mono mt-0.5 text-[9px] text-[#617167]">every field · auditable</p></div></div>
          </div>
        </div>
        <div className="absolute bottom-9 left-1/2 hidden -translate-x-1/2 items-center gap-2 text-[9px] uppercase tracking-[.2em] text-[#617167] sm:flex"><ArrowDown size={13} /> Explore the workspace</div>
      </section>

      <section className="border-y border-[#c7dcc9]/10 bg-[#0b100c]/70 py-4"><div className="mx-auto flex max-w-[1180px] flex-wrap items-center justify-between gap-6 px-6 text-[10px] uppercase tracking-[.16em] text-[#617167] lg:px-8"><span>Built for the people behind the numbers</span><span className="dm-display text-[15px] normal-case tracking-[-.04em] text-[#8d9d90]">Ledgerly</span><span className="dm-display text-[15px] normal-case tracking-[-.04em] text-[#8d9d90]">Rook & Co.</span><span className="dm-display text-[15px] normal-case tracking-[-.04em] text-[#8d9d90]">meridian</span><span className="dm-display text-[15px] normal-case tracking-[-.04em] text-[#8d9d90]">northstar</span></div></section>

      <section id="product" className="mx-auto max-w-[1180px] px-6 py-28 lg:px-8">
        <div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><span className="dm-mono text-[10px] uppercase tracking-[.22em] text-[#d9b66d]">A better starting point</span><h2 className="dm-display mt-5 max-w-[420px] text-4xl font-medium leading-[1.03] tracking-[-.06em] text-[#e8f0e5] md:text-5xl">Manual entry is a tax on your best people.</h2></div><p className="max-w-[460px] self-end text-[15px] leading-7 text-[#95a69a]">The work is important. The copying is not. DocuMind gives your team a calm, accountable place to turn unstructured documents into decisions.</p></div>
        <div className="mt-16 grid gap-4 md:grid-cols-3">{features.map(({icon: Icon, kicker, title, body, stat, label}) => <article key={kicker} className="dm-glass dm-glass-hover rounded-[22px] p-6 md:min-h-[345px]"><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#9df4b1]/20 bg-[#9df4b1]/[.08] text-[#9df4b1]"><Icon size={18} /></div><span className="dm-mono text-[10px] text-[#617167]">{kicker}</span></div><h3 className="dm-display mt-16 text-[24px] font-medium leading-tight tracking-[-.05em] text-[#e8f0e5]">{title}</h3><p className="mt-3 text-[12px] leading-5 text-[#95a69a]">{body}</p><div className="mt-8 border-t border-[#c7dcc9]/10 pt-4"><span className="dm-display text-2xl text-[#9df4b1]">{stat}</span><span className="ml-2 text-[10px] text-[#617167]">{label}</span></div></article>)}</div>
      </section>

      <section id="workflow" className="relative overflow-hidden border-y border-[#c7dcc9]/10 bg-[#0b100c]/50 py-28"><div className="pointer-events-none absolute right-0 top-0 h-full w-1/2 bg-[radial-gradient(ellipse_at_center,rgba(57,202,114,.09),transparent_65%)]" /><div className="relative mx-auto max-w-[1180px] px-6 lg:px-8"><div className="max-w-[500px]"><span className="dm-mono text-[10px] uppercase tracking-[.22em] text-[#d9b66d]">Three quiet moves</span><h2 className="dm-display mt-5 text-4xl font-medium leading-[1.03] tracking-[-.06em] text-[#e8f0e5] md:text-5xl">The busywork disappears. The signal stays.</h2></div><div className="mt-16 grid gap-0 lg:grid-cols-3">{[{n:"01",t:"Drop anything in.",b:"Invoices, receipts, POs, bank statements. A file, a folder, or a whole month of backlog."},{n:"02",t:"Let context do the work.",b:"DocuMind maps fields, line items, and relationships — not just text on a page."},{n:"03",t:"Move with confidence.",b:"Edit in place, export to your system, and keep a trace of how every value got there."}].map((x,i)=><div key={x.n} className="relative border-l border-[#c7dcc9]/15 px-7 py-2 first:border-l-0 first:pl-0 lg:min-h-[230px]"><span className="dm-mono text-[11px] text-[#9df4b1]">{x.n}</span><h3 className="dm-display mt-10 text-2xl tracking-[-.04em]">{x.t}</h3><p className="mt-3 max-w-[260px] text-[12px] leading-5 text-[#95a69a]">{x.b}</p>{i<2&&<MoveRight className="absolute -right-3 top-2 hidden text-[#d9b66d] lg:block" size={18}/>}</div>)}</div></div></section>

      <section id="pricing" className="mx-auto max-w-[1180px] px-6 py-28 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><span className="dm-mono text-[10px] uppercase tracking-[.22em] text-[#d9b66d]">Simple by design</span><h2 className="dm-display mt-5 text-4xl font-medium tracking-[-.06em] md:text-5xl">Start small. Scale cleanly.</h2></div><div className="flex items-center gap-1 rounded-full border border-[#c7dcc9]/15 bg-[#101812] p-1 text-[11px]"><button onClick={()=>setAnnual(false)} className={`rounded-full px-4 py-2 ${!annual?"bg-[#9df4b1] text-[#07110a]":"text-[#95a69a]"}`}>Monthly</button><button onClick={()=>setAnnual(true)} className={`rounded-full px-4 py-2 ${annual?"bg-[#9df4b1] text-[#07110a]":"text-[#95a69a]"}`}>Yearly <span className="ml-1 text-[#d9b66d]">−20%</span></button></div></div><div className="mt-14 grid gap-4 md:grid-cols-3"><Price name="Essentials" price={annual ? "$39" : "$49"} detail="For lean teams finding their rhythm." items={["500 pages / month","Core extraction fields","CSV & JSON export"]} /><Price name="Operations" price={annual ? "$129" : "$159"} detail="For teams with a real document flow." items={["2,500 pages / month","Custom field schemas","QuickBooks & NetSuite","Team review workspace"]} featured /><Price name="Scale" price="Let's talk" detail="For complex operations at volume." items={["Unlimited workspaces","Priority processing","SSO & audit controls","Dedicated success partner"]} /></div></section>

      <section className="mx-auto max-w-[1180px] px-6 pb-28 lg:px-8"><div className="dm-glass relative overflow-hidden rounded-[26px] px-7 py-14 text-center md:px-20"><div className="pointer-events-none absolute left-1/2 top-0 h-56 w-96 -translate-x-1/2 bg-[#39ca72]/10 blur-[90px]" /><span className="relative dm-mono text-[10px] uppercase tracking-[.2em] text-[#9df4b1]">Your next clear hour</span><h2 className="dm-display relative mx-auto mt-5 max-w-[650px] text-4xl font-medium leading-[1] tracking-[-.06em] md:text-6xl">Give your team their time back.</h2><p className="relative mx-auto mt-5 max-w-[430px] text-[13px] leading-6 text-[#95a69a]">A calmer way to process the documents your business runs on.</p><button onClick={()=>notify("Your free workspace is being prepared.")} className="dm-btn dm-btn-primary relative mt-8">Start for free <ArrowRight size={16}/></button></div></section>
      <footer className="border-t border-[#c7dcc9]/10"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-8 px-6 py-10 md:flex-row md:items-center lg:px-8"><div><Brand/><p className="mt-3 text-[11px] text-[#617167]">Structured clarity for the work behind the work.</p></div><div className="flex gap-6 text-[11px] text-[#617167]"><a href="#product" className="hover:text-[#e8f0e5]">Product</a><a href="#pricing" className="hover:text-[#e8f0e5]">Pricing</a><button onClick={()=>notify("Privacy center opened.")} className="hover:text-[#e8f0e5]">Privacy</button><button onClick={()=>notify("Contact form opened.")} className="hover:text-[#e8f0e5]">Contact</button></div><span className="dm-mono text-[10px] text-[#617167]">© 2024 DocuMind</span></div></footer>
      {toast && <Toast message={toast} onClose={()=>setToast("")}/>}
    </main>
  );
}

function FileTextIcon() { return <FileCheck2 size={18} strokeWidth={1.8} />; }
function MiniField({label,value,gold=false}:{label:string;value:string;gold?:boolean}) { return <div className="rounded-lg border border-[#c7dcc9]/10 bg-[#111a14] p-3"><p className="dm-mono text-[8px] uppercase tracking-[.12em] text-[#617167]">{label}</p><p className={`mt-1 text-[11px] font-semibold ${gold?"text-[#efd08d]":"text-[#e8f0e5]"}`}>{value}</p></div>; }
function Price({name,price,detail,items,featured=false}:{name:string;price:string;detail:string;items:string[];featured?:boolean}) { return <div className={`relative rounded-[22px] border p-6 ${featured?"border-[#9df4b1]/45 bg-[#122319] shadow-[0_0_60px_rgba(57,202,114,.1)]":"border-[#c7dcc9]/12 bg-[#0e1510]"}`}>{featured&&<span className="absolute -top-3 right-6 rounded-full bg-[#d9b66d] px-3 py-1 text-[9px] font-bold uppercase tracking-[.14em] text-[#211b0e]">Most popular</span>}<span className="dm-mono text-[10px] uppercase tracking-[.15em] text-[#9df4b1]">{name}</span><p className="mt-6 text-[12px] text-[#95a69a]">{detail}</p><p className="dm-display mt-5 text-4xl tracking-[-.06em]">{price}<span className="text-[12px] text-[#617167]">{price[0]==="$"&&"/ month"}</span></p><button className={`dm-btn mt-7 w-full ${featured?"dm-btn-primary":"dm-btn-ghost"}`}>Choose {name} <SmallArrow/></button><ul className="mt-7 space-y-3 border-t border-[#c7dcc9]/10 pt-6">{items.map(item=><li key={item} className="flex items-center gap-2 text-[11px] text-[#95a69a]"><Check size={13} className="text-[#9df4b1]"/>{item}</li>)}</ul></div>; }